#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &&
LC_CTYPE=zh_CN.UTF-8 emacs --daemon &
fcitx &
pcmanfm --daemon-mode &
udiskie -f pcmanfm &
bluetoothctl connect 38:18:4C:1A:3E:4B &
conky &
#easyeffects --gapplication-service &
dunst &
compfy -b &

if [ $HOSTNAME == home ]; then
    xrandr --output DP-0 --auto --primary --rotate inverted --output HDMI-0 --auto --below DP-0 &&
    feh --bg-fill --no-xinerama --no-fehbg .config/wallpaper/gruvbox_image31.png &
    bspc wm -O DP-0 HDMI-0
    
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8 9 0
elif [ $HOSTNAME == book ] || [ $HOSTNAME == pad ] || [ $HOSTNAME == suitcase ]; then
    setxkbmap -layout us -variant colemak_dh_ortho
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config pointer_modifier ctrl

bspc config border_width         2
bspc config normal_border_color "#006b76"
bspc config active_border_color "#006b76"
bspc config focused_border_color "#b3c4c6"

bspc config window_gap          6

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Steam state=floating 
bspc rule -a Pcmanfm state=floating
bspc rule -a Lollypop state=floating
bspc rule -a wechat.exe state=floating
