#! /bin/sh

xrandr --output HDMI-0 --auto --output DP-0 --auto --primary --above HDMI-0 --rotate inverted &&
pgrep -x sxhkd > /dev/null || sxhkd &&
compfy -b &
emacs --daemon &
ibus-daemon -rxRd &
pcmanfm --daemon-mode --no-desktop &
udiskie -f pcmanfm &
bluetoothctl connect 38:18:4C:1A:3E:4B &
conky &
easyeffects --gapplication-service &
feh --bg-fill --no-xinerama --no-fehbg .config/wallpaper/gruvbox_image31.png &

if [[ $HOSTNAME == home ]]; then
    bspc wm -O HDMI-0 DP-0
    
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8 9 0
elif [[ $HOSTNAME == book ]] || [[ $HOSTNAME == pad ]] || [[ $HOSTNAME == suitcase ]]; then
    setxkbmap -layout us -variant colemak_dh_ortho
fi

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config pointer_modifier ctrl

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Steam state=floating 
bspc rule -a Pcmanfm state=floating
